# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-19 05:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('dataset_name', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('size', models.FloatField()),
                ('store_folder', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=200, unique=True)),
                ('code_url', models.URLField()),
                ('command', models.TextField()),
                ('create_time', models.DateTimeField(verbose_name='Time Created')),
                ('run_time', models.DateTimeField(verbose_name='Time of the Last Run')),
                ('status', models.CharField(max_length=6000)),
                ('pid', models.CharField(max_length=2000)),
                ('data_used', models.ManyToManyField(to='jobs.Dataset')),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_name', models.CharField(max_length=20)),
                ('server_location', models.CharField(max_length=20)),
                ('server_cpus', models.IntegerField()),
                ('cpu_time', models.CharField(max_length=6000)),
                ('roots_data', models.CharField(max_length=50)),
                ('roots_src', models.CharField(max_length=50)),
                ('crdntl_user', models.CharField(max_length=50)),
                ('crdntl_domain', models.CharField(max_length=50)),
                ('crdntl_password', models.CharField(max_length=20)),
                ('data_hosted', models.ManyToManyField(to='jobs.Dataset')),
            ],
        ),
    ]
