# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-31 01:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20160729_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 31, 1, 39, 57, 160735, tzinfo=utc), verbose_name='Time Created'),
            preserve_default=False,
        ),
    ]
