# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-19 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20160818_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='job_running',
            field=models.ManyToManyField(to='jobs.Job'),
        ),
    ]
