# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-31 05:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_job_create_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataset',
            name='id',
        ),
        migrations.AlterField(
            model_name='dataset',
            name='dataset_name',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
