# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-04 04:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_auto_20160730_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='dataset_name',
            field=models.CharField(max_length=200, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
