# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-19 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_auto_20160819_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrunningonserver',
            name='pid',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
