# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-22 18:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_auto_20160819_1321'),
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(null=True, verbose_name='Time When the Process Starts')),
                ('pid', models.CharField(max_length=2000, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='jobrunningonserver',
            name='pid',
        ),
        migrations.AddField(
            model_name='process',
            name='job_spawning',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.JobRunningOnServer'),
        ),
    ]
