# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-06 07:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_dataset_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='cpu_util',
            field=models.CharField(default='100', max_length=500),
            preserve_default=False,
        ),
    ]
