# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-22 19:11
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_auto_20160822_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='log_file',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='process',
            name='pid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='process',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 22, 19, 11, 14, 914200, tzinfo=utc), verbose_name='Time When the Process Starts'),
            preserve_default=False,
        ),
    ]
