# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-22 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_auto_20160822_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='result_file',
            field=models.CharField(default='pvals.yml', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobrunningonserver',
            name='status',
            field=models.CharField(max_length=600, null=True),
        ),
    ]
