# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-10 02:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_server_cpu_util'),
    ]

    operations = [
        migrations.RenameField(
            model_name='server',
            old_name='cpu_util',
            new_name='cpu_time',
        ),
    ]
