# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-10 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_auto_20160809_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='cpu_time',
            field=models.CharField(max_length=6000),
        ),
    ]
