# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-23 07:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_jobrunningonserver_result_nums'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 23, 7, 38, 3, 85234, tzinfo=utc), verbose_name='Time When the Job Starts'),
            preserve_default=False,
        ),
    ]
