# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-10 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_auto_20160810_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='server_location',
            field=models.CharField(default='Berkeley', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='server',
            name='server_name',
            field=models.CharField(max_length=20),
        ),
    ]
