# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-23 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_job_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='start_time',
            field=models.DateTimeField(null=True, verbose_name='Time When the Job Starts'),
        ),
    ]
