# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-23 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0015_job_result_directory'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrunningonserver',
            name='cores_used',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
