# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-23 23:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0016_jobrunningonserver_cores_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrunningonserver',
            name='process_living',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='process',
            name='status',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
