# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-23 23:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0017_auto_20160823_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrunningonserver',
            name='cores_used',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='jobrunningonserver',
            name='process_living',
            field=models.IntegerField(null=True),
        ),
    ]
