# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-16 07:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0020_auto_20160915_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='crdntl_loginnode',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
